### ISSUE TITLE
can't find the bi-directional mamba

### ISSUE THREAD

**Issue by pengzhangzhi** [hustvl/Vim#11]
Hi there, your vim is impressive! I had a great read of the paper and the code! I am trying to follow the bi-directional mamba but can't find where the code is. I looked https://github.com/hustvl/Vim/blob/main/vim/models_mamba.py

**Comment by eclipse0922** [comment]
I am not the author of the paper.
They seem to have fixed the mamba_ssm code for bidirectional mamba.

```
 # bidirectional
assert bimamba_type == "v2"
```

https://github.com/hustvl/Vim/blob/main/mamba/mamba_ssm/modules/mamba_simple.py


The original mamba implementation doesnt have above the variable and related code.
https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/mamba_simple.py

**Comment by pengzhangzhi** [comment]
oh yeah！ thanks!

**Comment by 87831743Sakura** [comment]
The code indeed contains the implementation of the bidirectional Mamba module. However, why have I never executed these lines of code during debugging?

**Comment by 87831743Sakura** [comment]
The link https://github.com/hustvl/Vim/blob/main/mamba/mamba_ssm/modules/mamba_simple.py is also broken.

**Comment by arelkeselbri** [comment]
Try https://github.com/hustvl/Vim/blob/main/mamba-1p1p1/mamba_ssm/modules/mamba_simple.py

**Comment by MPCheng-ZW** [comment]
Hi!

Do you know  what's the meaning of self.if_bidirectional in models_mamba.py?
@eclipse0922 @87831743Sakura @arelkeselbri @pengzhangzhi @xinggangw 

Thanks!

**Comment by eclipse0922** [comment]
The meaning of self.if_bidirectional in models_mamba.py relates to a key innovation in the Vim (Vision Mamba) model, as described in the paper "Vision Mamba: Efficient Visual Representation Learning with Bidirectional State Space Model".
The original Mamba model was designed for 1D sequence data like text or audio, typically processed in a forward direction. However, images are inherently 2D data, which presents unique challenges when adapting sequence models to vision tasks.
Vim addresses this by using a bidirectional approach:

Images are first flattened into a 1D sequence of patches.
Instead of processing this sequence only in one direction, Vim uses bidirectional State Space Models (SSMs) in each block.
This means each block processes the sequence both forward and backward, allowing it to capture spatial relationships and long-range dependencies from multiple perspectives.

The self.if_bidirectional flag likely controls whether this bidirectional processing is enabled. When true, it would activate both the forward and backward SSMs, as well as the bidirectional convolutions described in the Vim architecture.
This bidirectional approach is crucial for tasks like object detection and segmentation, where understanding the global context and spatial structure of an image is important. It allows Vim to more effectively capture the 2D nature of image data within the framework of a sequence model.
It's worth noting that there are various approaches to adapting Mamba-like models for vision tasks, with different methods for processing 2D data. The bidirectional approach in Vim is one specific strategy to address this challenge.

Please read the VIM and recent survey papers for better understanding.

**Comment by MPCheng-ZW** [comment]
Thanks for your quick response.

So, should  the argument of 'if_bidirectional' be set to 'True' rather than 'False' ?

![1](https://github.com/user-attachments/assets/10f3a88f-7406-41ff-b365-27be731fd683)

**Comment by MPCheng-ZW** [comment]
> Thanks for your quick response.
> 
> So, should the argument of 'if_bidirectional' be set to 'True' rather than 'False' ?

Thanks for your quick response.

So, should the argument of 'if_bidirectional' be set to 'True' rather than 'False' ?

![1](https://github.com/user-attachments/assets/fc65d9ff-9fae-4450-b09c-fb59b7ff43fb)

![2](https://github.com/user-attachments/assets/1f29193c-23c8-48da-985d-5aa9a1c9f7a2)

@eclipse0922 Thank u!

**Comment by MPCheng-ZW** [comment]
> Thanks for your quick response.
> 
> So, should the argument of 'if_bidirectional' be set to 'True' rather than 'False' ?

Thanks for your quick response.

So, should the argument of 'if_bidirectional' be set to 'True' rather than 'False' ?

![1](https://github.com/user-attachments/assets/eead409b-1934-444d-b787-602e9368aa9a)

![2](https://github.com/user-attachments/assets/c95a8810-b643-4ae3-8bb0-47e6a60f227a)

Thanks!

**Comment by MPCheng-ZW** [comment]
> The meaning of self.if_bidirectional in models_mamba.py relates to a key innovation in the Vim (Vision Mamba) model, as described in the paper "Vision Mamba: Efficient Visual Representation Learning with Bidirectional State Space Model". The original Mamba model was designed for 1D sequence data like text or audio, typically processed in a forward direction. However, images are inherently 2D data, which presents unique challenges when adapting sequence models to vision tasks. Vim addresses this by using a bidirectional approach:
> 
> Images are first flattened into a 1D sequence of patches. Instead of processing this sequence only in one direction, Vim uses bidirectional State Space Models (SSMs) in each block. This means each block processes the sequence both forward and backward, allowing it to capture spatial relationships and long-range dependencies from multiple perspectives.
> 
> The self.if_bidirectional flag likely controls whether this bidirectional processing is enabled. When true, it would activate both the forward and backward SSMs, as well as the bidirectional convolutions described in the Vim architecture. This bidirectional approach is crucial for tasks like object detection and segmentation, where understanding the global context and spatial structure of an image is important. It allows Vim to more effectively capture the 2D nature of image data within the framework of a sequence model. It's worth noting that there are various approaches to adapting Mamba-like models for vision tasks, with different methods for processing 2D data. The bidirectional approach in Vim is one specific strategy to address this challenge.
> 
> Please read the VIM and recent survey papers for better understanding.

Thanks for your quick response.

So, should the if_bidirectional argument be set to True rather than False?

![1](https://github.com/user-attachments/assets/539f73da-3f6a-46b4-b6a5-b5e18a1814a4)

![2](https://github.com/user-attachments/assets/0b31af56-2f83-484c-9ddc-516bbf6b83fa)

Thanks! @eclipse0922

**Comment by eclipse0922** [comment]
I think so, yes 
If you want to take advantage from vim' key idea.

**Comment by MPCheng-ZW** [comment]
> I think so, yes If you want to take advantage from vim' key idea.

Okay! I got it, thank u!

**Comment by wei-doctor** [comment]
插眼
